"""Standard Webhooks signature verification — cross-implementation parity.

The expected signature headers below were generated by the ACTUAL TypeScript
signer (``packages/contracts/src/webhook-signing.ts``, via its byte-for-byte copy
``sdks/webhook-ingester/src/webhook-signing.ts``) so this Python implementation
is checked against the real platform output, not against itself. To regenerate,
run a one-off inside ``sdks/webhook-ingester``:

    import { signWebhook } from "./src/webhook-signing.js";
    signWebhook({ secret: SECRET_A, msgId: MSG_ID, timestamp: TIMESTAMP, payload: PAYLOAD });

Inputs and outputs used here (SECRET_B is a DIFFERENT secret, for rotation):

    SECRET_A       = "whsec_dGVzdC1zaWduaW5nLWtleS0zMi1ieXRlcy1sb25n"
    SECRET_B       = "whsec_cm90YXRpb24tc2VjcmV0LTMyLWJ5dGVzLWxvbmctdGVzdA"
    MSG_ID         = "msg_2xyzABC123"
    TIMESTAMP      = 1700000000
    PAYLOAD        = '{"id":"evt_test","type":"email.delivered","data":{"email_id":"txemail_1"}}'
    signWebhook(A) = "v1,txVPz2dd9nKoJKXT5SM0Ryfb0Tb5H+HRpz4nI/xpw+Q="
    signWebhook(B) = "v1,c1hy0+MUcGBKxkM1Y96IQmkXAe2lGJY2AeZIQvKBJvg="
"""

import unittest

from mailtea import sign_webhook, verify_webhook_signature

SECRET_A = "whsec_dGVzdC1zaWduaW5nLWtleS0zMi1ieXRlcy1sb25n"
SECRET_B = "whsec_cm90YXRpb24tc2VjcmV0LTMyLWJ5dGVzLWxvbmctdGVzdA"
MSG_ID = "msg_2xyzABC123"
TIMESTAMP = 1700000000
PAYLOAD = '{"id":"evt_test","type":"email.delivered","data":{"email_id":"txemail_1"}}'

# Cross-implementation fixtures produced by the TypeScript signer (see docstring).
HEADER_A = "v1,txVPz2dd9nKoJKXT5SM0Ryfb0Tb5H+HRpz4nI/xpw+Q="
HEADER_B = "v1,c1hy0+MUcGBKxkM1Y96IQmkXAe2lGJY2AeZIQvKBJvg="
# During rotation the platform signs with both secrets and sends both tokens.
ROTATION_HEADER = HEADER_A + " " + HEADER_B


class WebhookSigningTest(unittest.TestCase):
    # --- cross-implementation: Python signer reproduces the TS output exactly ---
    def test_sign_matches_typescript_vector_secret_a(self):
        self.assertEqual(
            sign_webhook(SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD), HEADER_A
        )

    def test_sign_matches_typescript_vector_secret_b(self):
        self.assertEqual(
            sign_webhook(SECRET_B, MSG_ID, TIMESTAMP, PAYLOAD), HEADER_B
        )

    def test_verify_accepts_typescript_signed_header(self):
        self.assertTrue(
            verify_webhook_signature(
                SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD, HEADER_A, now=TIMESTAMP
            )
        )

    def test_verify_accepts_string_timestamp(self):
        # The webhook-timestamp header arrives as a string.
        self.assertTrue(
            verify_webhook_signature(
                SECRET_A, MSG_ID, str(TIMESTAMP), PAYLOAD, HEADER_A, now=TIMESTAMP
            )
        )

    # --- bad signature rejected ---
    def test_verify_rejects_tampered_payload(self):
        self.assertFalse(
            verify_webhook_signature(
                SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD + " ", HEADER_A, now=TIMESTAMP
            )
        )

    def test_verify_rejects_wrong_secret(self):
        # HEADER_A was signed with SECRET_A; verifying with SECRET_B must fail.
        self.assertFalse(
            verify_webhook_signature(
                SECRET_B, MSG_ID, TIMESTAMP, PAYLOAD, HEADER_A, now=TIMESTAMP
            )
        )

    def test_verify_rejects_garbage_and_missing_version(self):
        self.assertFalse(
            verify_webhook_signature(SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD, "", now=TIMESTAMP)
        )
        self.assertFalse(
            verify_webhook_signature(
                SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD, "not-a-signature", now=TIMESTAMP
            )
        )
        # Right signature bytes but a version other than v1 is ignored.
        wrong_version = "v2," + HEADER_A.split(",", 1)[1]
        self.assertFalse(
            verify_webhook_signature(
                SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD, wrong_version, now=TIMESTAMP
            )
        )

    # --- expired / replay ---
    def test_verify_rejects_expired_timestamp(self):
        self.assertFalse(
            verify_webhook_signature(
                SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD, HEADER_A, now=TIMESTAMP + 10_000
            )
        )

    def test_verify_rejects_non_finite_timestamp(self):
        self.assertFalse(
            verify_webhook_signature(
                SECRET_A, MSG_ID, float("inf"), PAYLOAD, HEADER_A, now=TIMESTAMP
            )
        )

    # --- rotation: a header carrying both tokens verifies against either secret ---
    def test_verify_rotation_second_secret_matches(self):
        # Endpoint holds the NEW secret (B); the rotation header's second token
        # was signed with B, so verification passes.
        self.assertTrue(
            verify_webhook_signature(
                SECRET_B, MSG_ID, TIMESTAMP, PAYLOAD, ROTATION_HEADER, now=TIMESTAMP
            )
        )

    def test_verify_rotation_first_secret_matches(self):
        # Endpoint still holds the OLD secret (A); the first token matches.
        self.assertTrue(
            verify_webhook_signature(
                SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD, ROTATION_HEADER, now=TIMESTAMP
            )
        )

    # --- tolerance boundary ---
    def test_verify_tolerance_boundary(self):
        # Exactly at the default 300s tolerance passes; one second past fails.
        self.assertTrue(
            verify_webhook_signature(
                SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD, HEADER_A, now=TIMESTAMP + 300
            )
        )
        self.assertFalse(
            verify_webhook_signature(
                SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD, HEADER_A, now=TIMESTAMP + 301
            )
        )

    def test_verify_custom_tolerance(self):
        self.assertTrue(
            verify_webhook_signature(
                SECRET_A,
                MSG_ID,
                TIMESTAMP,
                PAYLOAD,
                HEADER_A,
                tolerance_seconds=10_000,
                now=TIMESTAMP + 5_000,
            )
        )


if __name__ == "__main__":
    unittest.main()
